// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynkmybzvohjyiqxouaqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlua215Ynp2b2hqeWlxeG91YXF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NTM4NTYsImV4cCI6MjA3MTUyOTg1Nn0._BgtoQn69K1-PguwPkKGglEEXEN7kkRTDvBF-cxlJ8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});